[package]
name = "websocket-motoko"
version = "0.0.1"
description = "IC WebSocket Motoko Impimentetion"
repository = ""
keywords = [ ]
license = "MIT"

[dependencies]
base = "0.9.1"
ic-certification = "0.1.1"
sha2 = "0.0.2"
cbor = "0.1.3"
ic-websocket-cdk = "https://github.com/omnia-network/ic-websocket-cdk-mo#1d3320626e3c476632fc46ebdb9b5402e6207999"
